src/agnocastlib/src/agnocast_multi_threaded_executor.cpp
MultiThreadedAgnocastExecutorのspin()内で、spinning変数のチェックが漏れていたので追加しました。また、チェック方法をSingleThreadedAgnocastExecutorと揃えました。
https://github.com/tier4/agnocast/blob/3db26d5181ab6e8de126098701b04c0d9d664a96/src/agnocastlib/src/agnocast_single_threaded_executor.cpp#L35
=> fix: checking spinning in MultiThreadedAgnocastExecutor

.github/workflows/cppcheck-differential.yaml
=> fix(kmod): ignore cppcheck for kunit

scripts/run_kunit
KUnitのテストがfailしている際にpre-commitもfailするように修正。
手元で正しく動作することを確認
=> fix: fail pre-commit when KUnit tests are not passed

kmod/agnocast.c, kmod/agnocast.h, src/agnocastlib/include/agnocast_ioctl.hpp
- updated `MAX_SUBSCRIBER_NUM` from 8 to 16, considering Autoware topics
- updated comments for `MAX_...` macros
- moved `MAX_MAP_NUM` from header to .c file
=> fix(kmod): update kernel module macros

kmod/CMakeLists.txt, kmod/package.xml, scripts/build_all
apt packageとして配布するために、colconのビルドシステム下でビルドする必要がある。
=> Build kmod under colcon

scripts/build_all, src/agnocast_heaphook/CMakeLists.txt, src/agnocast_heaphook/package.xml
apt packageとして配布するために、colconのビルドシステム下でビルドする必要がある。
package.xmlのメタデータは、リリース時に一斉に整備します。
手元のシステムで、heaphookのインストール場所が変わるので注意。
- `/lib/libagnocast_heaphook.so` (変更前)
- `install/agnocast_heaphook/lib/libagnocast_heaphook.so` (変更後)
変更前の場所にあるsoファイルを消しておくこと。
=> Build heaphook under colcon

kmod/agnocast.c
Solved cppcheck warnings `variableScope`
=> fix(kmod): fix variableScope cppcheck warnings

kmod/agnocast.c, kmod/agnocast.h
Solved cppcheck warnings `constVariablePointer`
=> fix(kmod): fix constVariablePointer cppcheck warnings

.cppcheck_suppressions
Suppress `uninitvar` cppcheck for agnocast.c
=> fix(cppcheck): suppress uninitvar for kernel module

README.md, scripts/build_all, scripts/setup
- Removed `build_all` script
- Removed cargo-deb installation
- Updated README
=> fix: remove unnecessary procedures

.cppcheck_suppressions, kmod/agnocast.c, kmod/agnocast.h, kmod/agnocast_kunit/agnocast_kunit_new_shm.c, kmod/agnocast_kunit/agnocast_kunit_new_shm.h
Added unit tests for `AGNOCAST_NEW_SHM_CMD`
I want to add `test_case_new_shm_too_big_size` test case which confirms whether `new_shm_addr` rejects too big shared memory allocation. However, the current implementation does not raise an error with such inputs.
I will refactor it and add the case later.
=> feat(kmod): unit test for AGNOCAST_NEW_SHM_CMD

src/agnocastlib/src/agnocast_executor.cpp
This fixes the bug that Agnocast's executor doesn't consider `CallbackGroupType::Reentrant`.
As far as I examined, `can_be_taken_from` is never false in `Reentrant`, but I am also checking in `Reentrant` just to be sure.
=> fix: for CallbackGroupType::Reentrant

agnocast_kmod/.gitignore, agnocast_kmod/Makefile, scripts/run_kunit
Separeted the build command for agnocast_kmod:
- `make` creates `agnocast.ko`
- `make test` creates `agnocast_kunit.ko`
This PR also solved the following small problems:
- remove temporary file for agnocast.c
- enable all compile options for `agnocast_kunit/*.o` objects
- add `PHONY` directive
=> feat(kmod): separete build for kunit

src/agnocast_e2e_test/test/test_1to1_with_ros2sub.py, src/agnocast_e2e_test/test/test_2to2.py
https://star4.slack.com/archives/C07FL8616EM/p1741155245733069?thread_ts=1741141942.114109&cid=C07FL8616EM
=> fix: not to check display order in e2e tests

src/agnocast_ioctl_wrapper/src/node_info.cpp
Remove `NOLINT` from agnocast_ioctl_wrapper, since they are no longer checked by clang-tidy.
=> fix(ioctl_wrapper): remove NOLINT

docs/ros2_command_extension.md
Add documents for `ros2agnocast` .
=> doc(ros2agnocast): documents for topic info and node info

.github/CODEOWNERS
=> chore: add TetsuKawa into ros2agnocast owner

agnocast_heaphook/build.rs, agnocast_heaphook/src/lib.rs, agnocast_heaphook/stub/lib.rs
v1.0.0リリースにて、agnocast_heaphookのビルド時にagnocatlibとリンクしないようにする変更を行なった (agnocast_heaphookはagnocastlibと独立した環境でリリースされるため、agnocast_heaphookビルド時のagnocastlibへの依存が不都合であったため)。
通常の動的リンクにおいては、未解決シンボルを探索するために、LD_LIBRARY_PATH等で指定されたパスを順番に探索して、最初にシンボルが見つかったライブラリに対してアドレスを解決する。
しかし、LD_PRELOADで指定したライブラリに関しては、そのライブラリで解決しないシンボルは、その時点でロードされているライブラリの中からしかシンボルを解決することができないという制約がある。つまり、探索パス上にlibagnocast.soが存在していたとしても、LD_PRELOADにagnocast_heaphook.soを指定したとき、agnocast_heaphook.so上で未解決になっているシンボルのアドレスを解決することはできない。
この問題に対処するためには、agnocast_heaphook.so ELFファイルのDT_NEEDEDにlibagnocast.soを記録すればいい。この場合は、LD_PRELOADで指定した場合にも、探索パスからlibagnocast.soを探し、未解決シンボルを解決してくれる。
これを実現するためには、ビルド時にlibagnocast.soと動的リンク ( `-lagnocast` ) すればいいが、これをしたくないからそもそもagnocast_heaphookのビルド時にagnocatlibとリンクしないようにする変更を行なったのであった。 …
=> fix(agnocast_heaphook): prepare stub to fix link error

agnocast_kmod/agnocast_main.c
Freed `node_name` s to avoid memory leak.
=> fix(kmod): free node_name to avoid memory leak

agnocast_kmod/agnocast_main.c
Avoid memory leaks of publisher/subscriber info structure when inserting them.
=> fix(kmod): avoid memory leak of pubsub info

agnocast_kmod/agnocast_main.c
=> fix(kmod): fix typo

.github/workflows/build-test-heaphook.yaml, .github/workflows/build-test.yaml
- Removed `steps.check_changes_rust.outputs.rust_changed` check in build-test workflow
- Moved cargo setting `CARGO_TERM_COLOR` from cpp to rust workflow
=> ci: refactor build-test

.github/workflows/build-test-heaphook.yaml, agnocast_heaphook/Cargo.toml, agnocast_heaphook/src/lib.rs, scripts/setup
- `LazyLock` is now in the stable version 1.85.0
- updated edtion to `2024`
- Rust version 1.85.0: https://releases.rs/docs/1.85.0/
- Edition: https://doc.rust-lang.org/nightly/edition-guide/editions/index.html
=> feat(agnocast_heapgook): update Rust environment

agnocast_heaphook/Cargo.toml
=> fix(heaphook): fix typo

scripts/e2e_test_stress
負荷を変動させつつ、長時間e2eテストを実行するスクリプトを実装しました。
bash scripts/e2e_test_stress
全ては見ていないですが、最初の数ループが正しく動作しているのを確認しました。
```bash
--cpu N               start N workers that perform CPU only loading
--cpu-load P          load CPU by P %, 0=sleep, 100=full load
--vm N                start N workers spinning on anonymous mmap
--vm-bytes N          allocate N bytes per vm worker (default 256MB)
--shm N               start N workers that exercise POSIX shared memory
--shm-bytes N         allocate/free N bytes of POSIX shared memory
--mq N                start N workers passing messages using POSIX
```
=> test: stress & long time test

agnocast_kmod/agnocast.h, agnocast_kmod/agnocast_main.c
Used `const` for const parameters.
const はビルドのみに影響し実行には関係ないので、各種動作確認は行なっていません :bow:
=> fix(kmod): make variables const if possible

agnocast_kmod/agnocast_main.c, agnocast_kmod/agnocast_memory_allocator.h
Refined `subscriber_add` related functions' return values.
Actually, there was a bug in `subscriber_add`:
when `set_publisher_shm_info` failed with exit code other than -1, `subscriber_add` does not fail since it cheks in the following way
```
if (set_publisher_shm_info(wrapper, sub_info->pid, &ioctl_ret->ret_pub_shm_info) == -1) {
return -1;
}
```
This is why `MAX_PROCESS_NUM_PER_MEMPOOL` is changed to 32.
=> fix(kmod): refine return values

agnocast_kmod/agnocast.h, agnocast_kmod/agnocast_main.c
Fixed `get_topic_entries_num` bug: it didn't properly calculate the total count of entries.
kunit tests pass
=> fix(kmod): fix get_topic_entries_num bug

agnocast_kmod/agnocast_kunit/agnocast_kunit_new_shm.c, agnocast_kmod/agnocast_kunit_main.c, agnocast_kmod/agnocast_main.c
Removed too much dmesg on kunit test:
- removed `dev_info(agnocast_device, "Process (pid=%d) has exited. (process_exit_cleanup)\n", pid);` from kunit
- changed the timing of `exit_memory_allocator` from test suite exit to test exit
- refactored `test_case_new_shm_too_many` test so that only one `new_shm` call will fail.
=> fix(kmod): remove too much dmesg on kunit test

agnocast_kmod/agnocast.h, agnocast_kmod/agnocast_main.c
receive_and_check_new_publisherのrenameとerrnoの設定を行いました。
Autowareでの動作確認後マージします
=> refactor(kmod): rename receive function and fix to appropriate errno

src/agnocast_e2e_test/CMakeLists.txt
=> fix: remove launch_testing_ament_cmake

agnocast_kmod/agnocast_main.c, src/agnocastlib/include/agnocast/agnocast_subscription.hpp
- skip transient local procedures on take subscription addition
- stop updating `sub_info->latest_received_entry_id` on transient_local, and use dummy entry_id
=> fix(kmod): skip transient_local procedures on take subscriber addition

agnocast_kmod/agnocast_kunit/agnocast_kunit_subscriber_add.c
Added `test_case_subscriber_add_too_many_mmap` kunit test.
=> test(kmod): add subscriber_add kunit test for too many mmap

agnocast_kmod/agnocast_main.c
Only fixed two error returning values in take_msg.
=> refactor(kmod): fix errno in take_msg

scripts/e2e_test_1to1_with_ros2sub, scripts/e2e_test_2to2, scripts/e2e_test_stress, src/agnocast_e2e_test/src/test_publisher.cpp, src/agnocast_e2e_test/src/test_ros2_subscriber.cpp, src/agnocast_e2e_test/src/test_subscriber.cpp, src/agnocast_e2e_test/src/test_take_subscriber.cpp, src/agnocast_e2e_test/test/test_1to1_with_ros2sub.py, src/agnocast_e2e_test/test/test_2to2.py
- e2e testの各テストケースのtimeout時間を設定可能に
- ログを /dev/kmsg に書き込むようにした
https://star4.slack.com/archives/C07FL8616EM/p1741312400130989
=> improve: stress test

agnocast_kmod/agnocast_main.c
fix entry_id init value to -1 so that it won't implies the actual entry_node.
=> fix(kmod): init entry_id used in take_msg

agnocast_kmod/agnocast_kunit/agnocast_kunit_increment_rc.c, agnocast_kmod/agnocast_kunit/agnocast_kunit_increment_rc.h
This pull request introduces a unit test for the increment_message_entry_rc function to verify its expected behavior. The test covers the following scenarios:
- Successfully incrementing the reference count (rc) when called with a valid pubsub_id that differs from the publisher.
- Ensuring that the function rejects attempts by the publisher to increment its own rc, returning an error (-1).
The primary goal of this test is to validate the correctness of increment_message_entry_rc, ensuring that it handles valid and invalid cases as expected.
=> test(kmod) Add test for increment_message_entry function

src/agnocast_e2e_test/src/test_subscriber.cpp, src/agnocastlib/include/agnocast/agnocast_executor.hpp, src/agnocastlib/include/agnocast/agnocast_multi_threaded_executor.hpp, src/agnocastlib/include/agnocast/agnocast_single_threaded_executor.hpp, src/agnocastlib/src/agnocast_component_container_mt.cpp, src/agnocastlib/src/agnocast_executor.cpp, src/agnocastlib/src/agnocast_multi_threaded_executor.cpp, src/agnocastlib/src/agnocast_single_threaded_executor.cpp
MultiThreadedAgnocastExecutorにて、agnocast callbackとros2 callbackが同一のMutuallyExclusive callback groupに属している時に**エラーで落ちる**ようにしました。prepare_epoll()時にチェックしているのは、executorがspin()した後でないと、callback groupへの登録が済んでいないケースがあるためです。厳密にはspin()後にもros2 callbackが参加してくる可能性がありますが、それはレアケースであるのと、callback実行時に毎回チェックするのはオーバヘッドが大きいので、現状の実装になっています。
これに伴い、 `get_next_ready_agnocast_executable()` で `wait_mutex_` を取らなくて良くなったので、ロジックを修正しました。また、e2eテストにおけるcbg分離も行いました。
- [CallbackGroup::collect_all_ptrs()](https://github.com/ros2/rclcpp/blob/19773973a80d753c6fa028b0b548462fbbef122d/rclcpp/src/rclcpp/callback_group.cpp#L57)
- [Discussion in Slack](https://star4.slack.com/archives/C07FL8616EM/p1741820412275869?thread_ts=1741756781.258029&cid=C07FL8616EM)
以下の凡ミスも修正しています
- protected -> private に変更できるものの移動
- パラメータのデフォルト値変更漏れ
=> feat: add validation if agnocast cb and ros2 cb belong to same MutuallyExclusive cbg in MultiThreadedAgnocastExecutor

scripts/e2e_test_stress
launch_testingではReadyToTest()が呼ばれたタイミングか、テストが終了したタイミングで対象プロセスがkillされてしまいます。なので、今回の用途ではReadyToTest()の遅延 (TimerActionのperiod) を伸ばすしかないのですが、
https://github.com/ros2/launch/blob/f31c1ff13fcbed3653d1a0e26438cb739e96d751/launch_testing/launch_testing/test_runner.py#L184 でこの値の上限がハードコーディングされているので、これをsedで書き換えるworkaroundを実装しました。
solves https://star4.slack.com/archives/C07FL8616EM/p1741861357582109?thread_ts=1741859385.045249&cid=C07FL8616EM
`bash scripts/e2e_test_stress`
=> fix: workaround for launch_testing timeout configuration

src/agnocastlib/CMakeLists.txt, src/agnocastlib/test/integration/include/node_for_no_starvation_test.hpp, src/agnocastlib/test/integration/src/node_for_no_starvation_test.cpp
https://github.com/tier4/agnocast/pull/515 により、agnocast callback と ros2 callback が同一Mutually Exclusive callback groupに所属できなくなったので、テストケースを少し修正しました。具体的には、callback group構成について以下のようなケースを検証しています：
- `individual`: 各callbackが独立したMutually Exclusive cbgに所属する
- `mutually_exclusive`: 全てのagnocast callbackは同一のMutually Exclusive cbgに所属、全てのros2 callbackは同一のMutually Exclusive cbgに所属する
- `reentrant`: 全てのagnocast callbackは同一のReentrant cbgに所属、全てのros2 callbackは同一のReentrant cbgに所属する
全てのcallbackが同一のReentrant cbgに属すケースは、テストする意味をそんなに感じなかったので実装していません。
=> fix(MultiThreadedAgnocastExecutor): restore starvation tests

src/agnocastlib/src/agnocast_executor.cpp, src/agnocastlib/src/agnocast_multi_threaded_executor.cpp, src/agnocastlib/src/agnocast_single_threaded_executor.cpp
https://github.com/tier4/agnocast/pull/515 により、このチェックは不要になりました。nullptrチェックのみ残しました。
https://star4.slack.com/archives/C07FL8616EM/p1741934476490689?thread_ts=1741917956.704529&cid=C07FL8616EM
=> improve(MultiThreadedAgnocastExecutor): remove unnecessary check

src/agnocastlib/include/agnocast/agnocast_publisher.hpp, src/agnocastlib/src/agnocast_publisher.cpp
closes #463 
This PR enables closing message queues (mqs) that are no longer needed.
A publisher no longer need an mq when the corresponding subscriber has exited. In this case, we close that mq.
`opened_mqs` の型を `unordered_map<string, mqd_t>` から `unordered_map<string, tuple<mqd_t, bool>>` に変更しました。毎回の `publish_core` 関数の呼び出しでその mq が使われたかどうかを、導入した `bool` で管理します。もし使われていなければ、その mq は close します。
ランタイムの allocation/deallocation を避けるため、情報（mq を close するかどうか）は `Publisher` のデータメンバに持たせる必要がありました。新しいデータメンバを用意するのは大袈裟だと思ったので、`opened_mqs_` が `bool` も保持できるようにすることで対応しました。
I confirmed that the sample talker closes the message queue when the sample listener is terminated first.
Since I am a beginner in C++, I might be making mistakes regarding resource management.
=> fix(agnocastlib): close mqs that are no longer needed

agnocast_kmod/agnocast_kunit/agnocast_kunit_take_msg.c, agnocast_kmod/agnocast_kunit/agnocast_kunit_take_msg.h
Removed `test_case_take_msg_too_many_rc` since incrementing reference count of invalid subscriber is no longer acceptable.
=> fix(kmod): remove invalid test

src/agnocast_e2e_test/test/test_2to2.py
クラウドのDocker環境など、ハードウェアのスレッド数が限られている場所では、2to2のテストが失敗する。
たとえば、物理スレッド数が2の環境では以下の理由で失敗する。
AgnocastMultiThreadedExecutorのデフォルト設定では、`ハードウェアのスレッド数 / 2` をスレッド数として、AgnocastとROS 2のスレッドプールを確保する。したがって、それぞれスレッド数は1。
そのため、 sleep 関数を呼び出すと、一つしかないスレッドの動作が停止し、全体が停止してしまう。
[slack](https://star4.slack.com/archives/C07FL8616EM/p1742285136146179?thread_ts=1742273836.154089&cid=C07FL8616EM)
https://github.com/tier4/agnocast/pull/538 がマージされないと、この設定変更は反映されない。
=> fix: e2e test in restricted environments in terms of the number of cores

.github/workflows/build-and-test-cpp.yaml, src/agnocastlib/test/unit/test_mocked_agnocast.cpp
https://github.com/tier4/agnocast/pull/476 でテストがfailするようになっていたので、修正しました。これは、 `git diff` が失敗しても添付画像のようにworkflowがpassしてしまうことに起因していたので、それを修正しました。
test
=> test: fix error & fail workflow when git diff is failed

src/agnocastlib/src/agnocast_component_container.cpp, src/agnocastlib/src/agnocast_component_container_mt.cpp
実は今まで、AgnocastのComponent Containerには、パラメータを渡せないバグがあった。
=> fix(component container): enable parameter passing

src/agnocastlib/test/integration/include/node_for_no_starvation_test.hpp, src/agnocastlib/test/integration/src/node_for_no_starvation_test.cpp, src/agnocastlib/test/integration/test_agnocast_multi_threaded_executor.cpp
`MultiThreadedAgnocastExecutor` の統合テストにcallback groupの仕様が守られているかのテストも加えました。当初はテストファイルやテスト用のノードをstarvationの検証と分けようと思っていたのですが、そのまま追加した方が実装が楽だったので、追加する形にしました。これに伴うもろもろのリネームは[別PR](https://github.com/tier4/agnocast/pull/543/files)で行います。
tests
=> test: add callback group validation into integration test

.github/workflows/cppcheck-differential.yaml, src/agnocastlib/src/agnocast_callback_info.cpp
Fixed cppcheck workflow bug: cppcheck was running for only kmod files.
=> fix(ci): fix bug in cppcheck workflow

agnocast_kmod/agnocast_main.c
Fixed bug on publisher exit: remove self reference of entry on publisher exit.
=> fix(kmod): remove publisher reference on publisher exit

agnocast_kmod/agnocast_kunit/agnocast_kunit_decrement_rc.c
Restored `test_case_decrement_rc_multi_reference` kunit test, which was previously commented out in https://github.com/tier4/agnocast/pull/520
=> fix(kmod): restore decrement_rc kunit test

agnocast_kmod/agnocast_kunit/agnocast_kunit_receive_msg.c
Restored `publisher_shm_info` assertions, which was changed in https://github.com/tier4/agnocast/pull/520
=> fix(kmod): restore receive_msg tests for publisher_shm_info

agnocast_kmod/agnocast_main.c, src/agnocastlib/src/agnocast.cpp
shm_unlinkをstruct Cleanupのデストラクタで行っているとAutowareの異常終了時にSIGABRTなどで終了される際に呼ばれないのでこれを解決するためにkernel moduleにおけるexit_handler内で行うように変更。また、kunitテスト時にはunlinkする必要はないので今回の追加はすべて#ifndef KUNIT_BUILDの元で実装している。
shm_unlinkは内部でunlinkat(2)を呼び出しているのでunlinkatに該当するカーネル内部の関数を直接呼び出す。
具体的にはそれは以下のdo_unlinkat()
https://elixir.bootlin.com/linux/v6.10.1/source/fs/namei.c#L4377
do_unlinkatはEXPORTされていないので、これを呼び出すためregister_kprobeを利用してdo_unlinkatのアドレスを直接取得している。
unlinkat(2)の定義
https://elixir.bootlin.com/linux/v6.10.1/source/fs/namei.c#L4449
ファイル名の文字列からstruct filenameを取得するgetnameの、カーネル内部呼び出し版のgetname_kernel
https://elixir.bootlin.com/linux/v6.10.1/source/fs/namei.c#L222
[TIER IV Internal Doc
](https://tier4.atlassian.net/wiki/spaces/CRL/pages/3603006119/dev+shm+dev+mqueue?force_transition=493ed30d-7f4b-464d-87fa-544b6f325e …
=> fix: do shm_unlink in kernel module

agnocast_kmod/agnocast_kunit/agnocast_kunit_take_msg.c
Restored publisher_shm_info assertions, which was changed in https://github.com/tier4/agnocast/pull/520
=> fix(kmod): restore take_msg tests for publisher_shm_info

agnocast_kmod/agnocast_main.c
Use larger hashbits for publisher/subscriber tables.
Based on generative AI,
> It is common practice to allocate a number of buckets that is approximately 1.3 to 2 times the amount of data to be stored.
=> fix(kmod): use larger hashtable for pub/sub

agnocast_heaphook/debian/control, agnocast_heaphook/src/lib.rs
次のリリースから、x64以外でのパッケージも配布する (kmodではすでに配布しているが、heaphookではx64だけのままになっていた)
=> fix(release): add arch in heaphook

agnocast_kmod/agnocast_kunit/agnocast_kunit_publish_msg.c, agnocast_kmod/agnocast_kunit/agnocast_kunit_publish_msg.h, agnocast_kmod/agnocast_main.c
publish_msgにおけるreturn valueに適切なerrnoを設定しました。
加えて、
- Unreachableなら"Unreachable:" の記載
- 本変更によるKunitテストの修正
- kunitテストの名前をtest_case_***からtest_case_publish_msg_***に変更
close #379
=> fix(kmod): fix publish_msg return value

src/agnocastlib/include/agnocast/agnocast_subscription.hpp
`takeData` の返り値は、 [Autowareの本家実装](https://github.com/autowarefoundation/autoware_universe/blob/0814577085282222bffc6d704a128998938f8eee/common/autoware_universe_utils/include/autoware/universe_utils/ros/polling_subscriber.hpp#L77) では、 `MessageT::ConstSharedPtr` である (つまり `std::shared_ptr<const MessageT>` )。本家側と返り値の型を合わせないと、AutowareをAgnocast enabled/disabledでビルドを切り替えたときに、型の齟齬が生じてしまう。
=> fix(agnocastlib): update the take function type to match the original

agnocast_kmod/agnocast_kunit/agnocast_kunit_receive_msg.c, agnocast_kmod/agnocast_kunit/agnocast_kunit_receive_msg.h
There was no test case for receive_msg which pass the following if branch
=> test(kmod): add missing test case for receive_msg

agnocast_kmod/agnocast_kunit/agnocast_kunit_do_exit.c, agnocast_kmod/agnocast_kunit/agnocast_kunit_do_exit.h
There was no test case for `do_exit` to pass the following if branch
=> test(kmod): add missing test case for do_exit

agnocast_kmod/agnocast_kunit/agnocast_kunit_receive_msg.c, agnocast_kmod/agnocast_kunit/agnocast_kunit_take_msg.c
Added the missing test for too many mapping processes in take_msg  and receive_msg.
This is a revised version of PR #514 which was implemented for subscriber_add kunit tests previously.
PR #514
Checked that the kunit test works.
=> feat(kmod): add kunit test for too many mapping processes in take_msg and receive_msg

agnocast_kmod/agnocast_main.c
Removed `pub_info->exited` since it is equivalent to the existence of process_info.
=> fix(kmod): remove pub_info->exited

src/agnocastlib/test/integration/src/initialize_shutdown_mock.cpp
#557 においてテストでのみ利用されるinitialize_agnocastのmock用関数においてビルド時にwarningが出力されていたのでそのsuppressをしました。
#557
=> fix(test): suppress warning for unused variable

agnocast_kmod/agnocast.h, agnocast_kmod/agnocast_main.c, src/agnocast_ioctl_wrapper/src/agnocast_ioctl.hpp, src/agnocastlib/include/agnocast/agnocast_ioctl.hpp
`#define AGNOCAST_SUBSCRIBER_ADD_CMD _IOW('S', 1, union ioctl_subscriber_args)`
デバドラのマジックナンバー(ioctlのコマンドの、例えば上における'S')はデバドラ内で基本的には統一されるようなので一応統一しました。また、なるべく既存のデバドラの利用している番号とはかぶらないように選ぶべきなようなので一応下のLinuxのDocumentationに挙げられているものは避けて、0xA6を選びました。(適当です。) 
https://elixir.bootlin.com/linux/v6.13/source/Documentation/userspace-api/ioctl/ioctl-number.rst
またコマンド番号(上の例における1)は一般的には1からインクリメンタルにつけていくようですが、ros2agnocast用のコマンドは20以降をつけています。これは今後の拡張性のための余裕をもたせる意図です。
=> refactor(kmod): unified magic number for ioctl

agnocast_kmod/agnocast_kunit/agnocast_kunit_receive_msg.c, agnocast_kmod/agnocast_kunit/agnocast_kunit_receive_msg.h, agnocast_kmod/agnocast_kunit/agnocast_kunit_take_msg.c, agnocast_kmod/agnocast_kunit/agnocast_kunit_take_msg.h, agnocast_kmod/agnocast_main.c
When `receive_msg`, it gets message entry but does not mmap shared memory for exited publisher.
This PR solved the problem and added kunit tests.
=> fix(kmod): bug when receive/take msgs after publisher exits

agnocast_heaphook/src/lib.rs, docs/autoware_integration.md, docs/how_to_set_environment_variables.md, docs/shared_memory.md, scripts/e2e_test_many_exit, src/agnocast_e2e_test/test/test_1to1_with_ros2sub.py, src/agnocast_e2e_test/test/test_2to2.py, src/agnocast_sample_application/launch/listener.launch.xml, src/agnocast_sample_application/launch/talker.launch.xml, src/agnocastlib/CMakeLists.txt, src/agnocastlib/test/unit/test_agnocast_utils.cpp
Preplace `MEMPOOL_SIZE` for `AGNOCAST_MEMPOOL_SIZE`
=> fix: use AGNOCAST prefix for MEMPOOL_SIZE

src/agnocastlib/src/agnocast_multi_threaded_executor.cpp, src/agnocastlib/src/agnocast_single_threaded_executor.cpp
This adds the `agnocast_construct_executor` traceponits for CARET.
=> feat: add agnocast_construct_executor tracepoints

src/agnocastlib/CMakeLists.txt
Autoware適用のときに、targetとprojectの名前が統一されていないと不都合が生じる場面があったので、統一する。
=> fix(agnocastlib): unify the target name with the project name

agnocast_kmod/agnocast_main.c
topic_wrapperはtopic_structとchar* topic_nameを結びつけるものであるべきなので、current_entry_id/current_pubsub_idはtopic_structに移しました。
=> refactor(kmod): Move current_pubsub_id & current_entry_id to topic_struct

README.md, agnocast_kmod/agnocast.h, agnocast_kmod/agnocast_kunit_main.c, agnocast_kmod/agnocast_main.c
Removed agnocast sysfs.
This is because most of their functionalities are replaced by ros2agnocast.
=> fix: remove agnocast sysfs

src/agnocastlib/CMakeLists.txt, src/agnocastlib/test/unit/test_mocked_agnocast.cpp
To solve this [issue](https://star4.slack.com/archives/C07FL8616EM/p1743460649530579), this refactors the unit tests not to use gmock-global.
=> refactor(test): not to use gmock-global

agnocast_kmod/agnocast_main.c
現状getname_kernelはLinux kernel v6.3以上でのみEXPORTされている関数であり、v6.2以下に対応するためkprobeを利用した実装に変更した。
shm_unlinkを現状kernel module内で行っているのでgetname_kernelもkernel moduleで行う必要があったが、shm_unlinkはいずれデーモン化されるので一時的なpatchである。
https://github.com/autowarefoundation/autoware/pull/5985
=> fix(kmod): support getname_kernel for linux kernel version below 6.2

agnocast_kmod/agnocast_main.c
topic namespace separation is based on net_ns currently, but this PR fix it to refer to ipc_ns.
PR #583 
[Background: TIER IV Internal Slack](https://star4.slack.com/archives/C07FL8616EM/p1743664016890479?thread_ts=1742797827.017589&cid=C07FL8616EM)
dockerのコンテナを作って同じコンテナ内で通信が可能なこと
dockerコンテナ実行時に--ipc=host, --pid=hostを付与した場合にコンテナとホストが通信可能
dockerコンテナ実行時に--ipc=hostを付与しなければコンテナとホストは通信可能ではない
dockerコンテナ実行時に--ipc=hostを付与せずにコンテナとホストそれぞれでpub/subを両方たててそれぞれの通信が閉じていることを確認。(ros2agnocastコマンドも利用してtopicが見えないことも確認。)
=> fix(kmod): topic namespace based on ipc_ns not net_ns

agnocast_kmod/agnocast.h, agnocast_kmod/agnocast_kunit/agnocast_kunit_decrement_rc.c, agnocast_kmod/agnocast_kunit/agnocast_kunit_do_exit.c, agnocast_kmod/agnocast_kunit/agnocast_kunit_get_subscriber_num.c, agnocast_kmod/agnocast_kunit/agnocast_kunit_increment_rc.c, agnocast_kmod/agnocast_kunit/agnocast_kunit_publish_msg.c, agnocast_kmod/agnocast_kunit/agnocast_kunit_publisher_add.c, agnocast_kmod/agnocast_kunit/agnocast_kunit_receive_msg.c, agnocast_kmod/agnocast_kunit/agnocast_kunit_subscriber_add.c, agnocast_kmod/agnocast_kunit/agnocast_kunit_take_msg.c, agnocast_kmod/agnocast_main.c
ipc_nsに関するrefactoring PR。
- ipc_nsに関連する処理をifndef KUNIT_BUILDから外し、kunit build時にも利用するよう変更。
- ipc_nsをcurrent->nsproxy->ipc_nsのように毎回取得するのではなく、pid同様agnocast_ioctl冒頭で取得してそれを各関数に引数で渡すように変更
- 上にともなって各テストの関数にipc_nsを渡すように変更
- current->...は静的に決まらないのでグローバル変数は利用できない
- 各関数冒頭で取得してそれを利用することも考えたが、変更範囲が多く作業が大変だったため文字列を一括で変換できるcurrent->nsproxy->ipc_nsを毎回取得する記法で一旦対応。(必要あれば今後のkunitテストのリファクタリングで対応。)
=> refactor(kmod): get ipc_ns in agnocast_ioctl

README.md
The path was previously shown as "script", but has been corrected to "scripts" to reflect the actual directory structure.
=> Fix typo related to KUnit execution in README

src/agnocastlib/src/agnocast_publisher.cpp, src/agnocastlib/test/unit/test_mocked_agnocast.cpp
See https://tier4.atlassian.net/wiki/spaces/CRL/pages/3630565680/20250408+Agnocast+Sync and https://star4.slack.com/archives/C07FL8616EM/p1744164837355909.
=> fix(Publisher): workaround for only calling borrow_loaned_message()

agnocast_kmod/agnocast_kunit/agnocast_kunit_decrement_rc.c, agnocast_kmod/agnocast_kunit/agnocast_kunit_do_exit.c, agnocast_kmod/agnocast_kunit/agnocast_kunit_publisher_add.c, agnocast_kmod/agnocast_kunit/agnocast_kunit_receive_msg.c, agnocast_kmod/agnocast_kunit/agnocast_kunit_subscriber_add.c, agnocast_kmod/agnocast_kunit/agnocast_kunit_take_msg.c
PR #603 でget_topic_numはstruct ipc_namespace*を引数に取るように変更されていたが、それがkunitテストには反映されていなかったので修正。
PR #603
=> fix(kunit): get_topic_num wasn't updated in kunit test

src/agnocastlib/src/agnocast_publisher.cpp
=> fix(agnocastlib): close agnocast fd when exit

agnocast_kmod/Makefile, agnocast_kmod/agnocast.h, agnocast_kmod/agnocast_main.c, src/agnocastlib/include/agnocast/agnocast_ioctl.hpp
ioctlのコマンドの数値的な順番を以下のように変更。
```
#define AGNOCAST_GET_VERSION_CMD _IOR(0xA6, 1, struct ioctl_get_version_args)
#define AGNOCAST_ADD_PROCESS_CMD _IOWR(0xA6, 2, union ioctl_add_process_args)
#define AGNOCAST_ADD_SUBSCRIBER_CMD _IOWR(0xA6, 3, union ioctl_add_subscriber_args)
#define AGNOCAST_ADD_PUBLISHER_CMD _IOWR(0xA6, 4, union ioctl_add_publisher_args)
#define AGNOCAST_INCREMENT_RC_CMD _IOW(0xA6, 5, struct ioctl_update_entry_args)
#define AGNOCAST_DECREMENT_RC_CMD _IOW(0xA6, 6, struct ioctl_update_entry_args)
#define AGNOCAST_PUBLISH_MSG_CMD _IOWR(0xA6, 7, union ioctl_publish_msg_args)
#define AGNOCAST_RECEIVE_MSG_CMD _IOWR(0xA6, 8, union ioctl_receive_msg_args)
#define AGNOCAST_TAKE_MSG_CMD _IOWR(0xA6, 9, union ioctl_take_msg_args)
```
=> refactor(kmod): reorder ioctl command

agnocast_kmod/agnocast_main.c
=> fix(kmod): fix check_daemon_necessity defining location

agnocast_heaphook/src/lib.rs
implementation of the unit test of the posix_memalign function included in agnocast_heaphook
=> test(heaphook): add unit test for posix_memalign function

agnocast_heaphook/src/lib.rs
implementation of the unit test of the aligned_alloc function included in agnocast_heaphook
=> test(heaphook): add unit test for aligned_alloc function

agnocast_kmod/agnocast_kunit/agnocast_kunit_add_process.c
This PR updates the kunit constant to reflect the new maximum process numbers set in commit d05c230.
=> fix(kunit): update the max process number

agnocast_heaphook/src/lib.rs
implementation of the unit test of the memalign function included in agnocast_heaphook
=> test(heaphook): add unit test for memalign function

src/agnocastlib/include/agnocast/agnocast_publisher.hpp, src/agnocastlib/src/agnocast_publisher.cpp, src/agnocastlib/test/unit/test_mocked_agnocast.cpp
To avoid unnecessary string creation, changed to use `topic_local_id_t` as the key for `opened_mqs`.
=> Change to use topic_local_id_t as the key for opened_mqs

src/agnocastlib/include/agnocast/agnocast_executor.hpp, src/agnocastlib/include/agnocast/agnocast_subscription.hpp, src/agnocastlib/src/agnocast.cpp, src/agnocastlib/src/agnocast_executor.cpp
=> fix: lock for atomically obtain shmem info via ioctl and do mmap

agnocast_kmod/agnocast_kunit/agnocast_kunit_receive_msg.c, agnocast_kmod/agnocast_kunit/agnocast_kunit_take_msg.c, agnocast_kmod/agnocast_main.c
This PR adds a boundary check for the `msg_virtual_address` argument in `publish_msg`.
kunit test のソースコードを修正しましたが、テストの意図に反する変更ではないか確認していただきたいです。
=> fix(kmod): add a boundary check for msg_virtual_address

agnocast_kmod/agnocast_main.c
Previously, the topic name and node name buffers were allocated on the stack. They are now allocated using kmalloc.  
This change is necessary because the frame size of `agnocast_ioctl` exceeds 1024 bytes when built with Linux kernel 6.14.1 (KASAN enabled).
- https://star4.slack.com/archives/C07FL8616EM/p1746317300901999
=> refactor(kmod): allocate memory for the name buffers using kmalloc

src/agnocastlib/include/agnocast/agnocast_subscription.hpp, src/agnocastlib/src/agnocast_subscription.cpp
This PR renames `mq_subscription` to `mq_subscription_` to conform to the Google C++ Style Guide.  
It also updates an outdated comment in the `remove_mq` function.
=> style: add a trailing underscore to the data member of Subscriber

README.md
This PR updates the troubleshooting section to mention the maximum number of message queues.
Shall we close #462?
=> docs: add note about message queue count limit to troubleshooting

src/agnocastlib/src/agnocast_publisher.cpp
This PR lowers the log level from ERROR to WARN when `mq_open` in the `publish_core` function fails. Please refer to the added comment for the rationale.
=> refactor(agnocastlib): lower the log level when mq_open fails

src/agnocastlib/include/agnocast/agnocast_executor.hpp
=> fix(agnocastlib): use override keyword

src/agnocastlib/include/agnocast/agnocast_executor.hpp, src/agnocastlib/include/agnocast/agnocast_multi_threaded_executor.hpp, src/agnocastlib/include/agnocast/agnocast_single_threaded_executor.hpp, src/agnocastlib/src/agnocast_executor.cpp, src/agnocastlib/src/agnocast_multi_threaded_executor.cpp, src/agnocastlib/src/agnocast_single_threaded_executor.cpp
This is the first pull request to begin integrating the [CallbackIsolatedExecutor](https://github.com/tier4/callback_isolated_executor) into Agnocast.  
The `CallbackIsolatedAgnocastExecutor` is designed as "a set of `SingleThreadedAgnocastExecutor` instances, each dedicated to a single callback group."
The challenge in implementing this model lies in the current Agnocast design, which assumes only one executor per process. This assumption makes it impossible to poll only Agnocast callbacks belonging to a specific callback group.
This pull request enables a `SingleThreadedAgnocastExecutor` to be dedicated to a specific callback group.
[TIER IV Internal](https://tier4.atlassian.net/wiki/spaces/CRL/pages/3815211404/CallbackIsolatedAgnocastExecutor)
=> feat(agnocastlib): single threaded executor for cie

agnocast_heaphook/src/lib.rs
Fixed memory-related functions to match the semantics of C:
- Modified to use `Layout` to ensure the alignment is a power of two.
- Fixed `realloc(ptr, size)` so that when ptr is not `NULL` and size is zero, it behaves equivalently to `free(ptr)`.
- Fixed `aligned_alloc` so that the size is a multiple of the alignment.
- Fixed `posix_memalign` so that the alignment is a multiple of two and also a multiple of `sizeof(void *)`.
See:
https://linux.die.net/man/3/posix_memalign
https://linux.die.net/man/3/malloc
I will create the unit tests in a separate PR.
=> fix(heaphook): fix memory-related functions to match C semantics

src/agnocastlib/CMakeLists.txt
This PR adds support for building with Clang.
When building `agnocastlib` with Clang (`clang-15` in my case), the following compiler errors occur (excerpt):
```
/opt/ros/humble/include/rclcpp/rclcpp/client.hpp:550:10: error: no member named 'optional' in namespace 'std'
std::optional<CallbackInfoVariant>
...
/opt/ros/humble/include/rclcpp/rclcpp/client.hpp:788:36: /opt/ros/humble/include/rclcpp/rclcpp/client.hpp:550:19: error: no template named 'variant' in namespace 'std'
error:   using CallbackInfoVariant = std::variant<
...
```
This is a result of Clang not finding standard library headers because no C++ standard has been set.
This PR sets the C++ standard to 17 if not set already, and now `agnocastlib` builds fine with Clang.
Steps to reproduce:
```bash
sudo apt update
sudo apt …
```
=> build: set C++ standard explicitly to support Clang builds

agnocast_heaphook/src/lib.rs, agnocast_heaphook/src/tlsf.rs
In the current implementation, we only support the TLSF allocator. As a first step toward supporting custom memory allocators in the future, I have defined a trait for memory allocators.
Although it may look like there are many changes, the only essential modification is the introduction of the trait. The TLSF-related definitions have been moved into tlsf.rs.
=> feat(heaphook) Define `AgnocastSharedMemoryAllocator` trait to support custom memory allocators

agnocast_kmod/agnocast_main.c
=> fix(kmod): add node name log for  insert_publisher/subscriber_info

agnocast_heaphook/src/lib.rs
In the current implementation, when `realloc` is called on shared memory, and `should_use_original_func` returns true, glibc’s `malloc` will be invoked. 
```rust
#[cfg(not(test))]
fn should_use_original_func() -> bool {
extern "C" {
fn agnocast_get_borrowed_publisher_num() -> u32;
}
if IS_FORKED_CHILD.load(Ordering::Relaxed) {
return true;
}
unsafe {
if agnocast_get_borrowed_publisher_num() == 0 {
return true;
}
}
false
}
```
```rust
match (is_shared, should_use_original) {
(true, true) => {
// In the child processes, ignore the free operation to the shared memory.
(*ORIGINAL_MALLOC.get_or_init(init_original_malloc))(new_size)
}
```
This happens in the following cases:
| is_shared  | IS_FORKED_CHILD | agnocast_get_borrowed_publisher_num() == 0 |
| :---: | :---: | :---: |
| 1 | 1 | 0 |
| 1 …
=> fix(heaphook): Handle unexpected `realloc` by returning null
