tier4/agnocast

- kmod/agnocast_kunit/agnocast_kunit_get_subscriber_num.c
- kmod/agnocast_kunit/agnocast_kunit_subscriber_add.c
After https://github.com/tier4/agnocast/pull/436, kunit test doesn't pass.
This PR fixes it.
> fix(kmod): align page size

- kmod/package.xml
- src/agnocast_heaphook/package.xml
> Delete unnecessary dependency

- kmod/package.xml
- ros2agnocast/package.xml
- src/agnocast_heaphook/package.xml
- src/agnocast_ioctl_wrapper/package.xml
- src/agnocastlib/package.xml
- src/e2e_test/package.xml
- src/sample_application/package.xml
- src/sample_interfaces/package.xml
> Update package metadata

- .cppcheck_suppressions
- .github/workflows/cppcheck-differential.yaml
- README.md
- scripts/run_kunit
https://github.com/tier4/agnocast/pull/459
> fix: related to release

- agnocast_kmod/agnocast.c
- agnocast_kmod/agnocast.h
This PR adds ioctl cmd for topic info command.
> feat(kmod): add get topic pub sub cmd

- src/agnocastlib/CMakeLists.txt
低確率で統合テストがfailする問題があるので、一旦コメントアウトします。
> chore: comment out multi-threaded executor tests

- .github/workflows/build-and-test-heaphook.yaml
- agnocast_heaphook/Cargo.toml
- agnocast_heaphook/src/lib.rs
- scripts/setup
For https://github.com/tier4/agnocast/pull/499
> fix(agnocast_heaphook): downgrade rust

- src/agnocastlib/src/agnocast_multi_threaded_executor.cpp
https://github.com/tier4/agnocast/pull/515 により不要になった。
> improve: remove old comment

- agnocast_kmod/agnocast_main.c
Unified topic add operations in subscriber_add and publisher_add.
Also, `Topic (topic_name=%s) already exists.` dmesg is removed.
> fix(kmod): unify topic add

- scripts/releases/prepare_release_kmod
> fix(script): modify kmod release script

- agnocast_heaphook/src/lib.rs
closes #466
以前は tlsf 初期化のため heaphook の malloc の中でオリジナルの malloc を呼び出す必要があった。`HOOKED` はそのために使われていたが、`__libc_start_main` で初期化コードを実行するようになったので現在は使われていない。
パッケージとして配布されている agnocast-heaphook をアンインストールし、`install/agnocastlib/lib/` から `/usr/lib/` に `libagnocast_heaphook.so` をコピーした状態でテストした。
> refactor(heaphook): remove the HOOKED thread-local

- README.md
- scripts/setup
> fix: update README

- agnocast_kmod/agnocast_main.c
Removed unnecessary `find_process_info(subscriber_pid);` call.
It is found through coverage report:
> fix(kmod): remove unncessary find_process_info

- agnocast_kmod/agnocast_kunit/agnocast_kunit_receive_msg.c
> fix(kmod): kunit build error

- .github/pull_request_template.md
> chore: add kunit tests into pull_request_template.md

- src/agnocastlib/src/agnocast.cpp
> fix(agnocastlib): tidy up error messages

- README.md
Added below
> rm /dev/mqueue/agnocast_to_ros2@*
> docs: add missing step in troubleshooting

- src/agnocastlib/include/agnocast/agnocast_subscription.hpp
See https://star4.slack.com/archives/C07FL8616EM/p1743646854353349.
> feat(TakeSubscription): add take_data

- .github/workflows/build-and-test-agnocastlib-heaphook.yaml
- agnocast_heaphook/src/lib.rs
Add unit test base for agnocast_heaphook
> test(heaphook): add unit test

- scripts/e2e_test_stress
https://star4.slack.com/archives/C07FL8616EM/p1744253251927799?thread_ts=1744172890.705859&cid=C07FL8616EM
> fix(stress_test): stop immediately if tests fail

- .github/workflows/build-and-test-agnocastlib-heaphook.yaml
- .github/workflows/build-kmod.yaml
https://star4.slack.com/archives/C07FL8616EM/p1744354435668209?thread_ts=1744353380.584289&cid=C07FL8616EM
> fix(ci): abort workflow if git diff fails

- agnocast_heaphook/src/lib.rs
implementation of the unit test of the realloc function included in agnocast_heaphook
> test(heaphook): add unit test for realloc function

- src/agnocast_e2e_test/src/test_publisher.cpp
This solves [this issue](https://star4.slack.com/archives/C07FL8616EM/p1745227240683709).
> fix(e2e test): extend waiting time for receiving transient local messages

- agnocast_heaphook/src/lib.rs
- agnocast_kmod/agnocast_memory_allocator.c
- agnocast_kmod/agnocast_memory_allocator.h
https://star4.slack.com/archives/C07FL8616EM/p1745467831520569?thread_ts=1745413717.826689&cid=C07FL8616EM
> fix(memory_allocator): increase mempoll size

- src/agnocast_e2e_test/test/test_1to1_with_ros2sub.py
Solved this issue. ([TIER IV Internal Slack](https://star4.slack.com/archives/C07FL8616EM/p1745227240683709))
> fix(e2e_test): extend ready_delay waiting time

- agnocast_heaphook/debian/changelog
- agnocast_heaphook/debian/control
- agnocast_kmod/debian/changelog
- agnocast_kmod/debian/control
- agnocast_kmod/debian/rules
- scripts/releases/prepare_release_heaphook
- scripts/releases/prepare_release_kmod
- scripts/releases/release_heaphook
- scripts/releases/release_kmod
- scripts/setup
> patch level ppa package

- src/agnocastlib/src/agnocast_executor.cpp
https://star4.slack.com/archives/C07FL8616EM/p1746707648487639
> fix: add validation for add_node()

- agnocast_heaphook/src/lib.rs
Add memory limit tests for heaphook to verify proper error handling when requesting huge allocations.
> test(heaphook): add unit tests for memory allocation limits

- .github/workflows/build-and-test-agnocastlib-heaphook.yaml
> fix: minor of workflow

- src/agnocastlib/test/integration/test_agnocast_heaphook.cpp
Add integration tests to verify that fork memory allocation works correctly in the agnocast heaphook system.
Mainly handled within heaphook
```rust
extern "C" fn post_fork_handler_in_child() {
IS_FORKED_CHILD.store(true, Ordering::Relaxed);
}
```
```rust
fn should_use_original_func() -> bool {
if IS_FORKED_CHILD.load(Ordering::Relaxed) {
return true;
}
unsafe {
if agnocast_get_borrowed_publisher_num() == 0 {
return true;
}
}
false
}
```
```rust
match (is_shared, is_forked_child) {
(true, true) => (), // In the child processes, ignore the free operation to the shared memory
(true, false) => tlsf_deallocate_wrapped(non_null_ptr),
(false, _) => (*ORIGINAL_FREE.get_or_init(init_original_free))(ptr),
}
```
So The tests verify that these three functions work correctly:
1. IS_FORKED_CHILD flag …
> test(integration): Add integration test investigate malloc region differences after fork
